defmodule Citadel.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workspaces) do
      add :task_prefix, :text
    end

    # Backfill existing workspaces with prefix derived from name
    execute """
    UPDATE workspaces
    SET task_prefix = UPPER(SUBSTRING(REGEXP_REPLACE(name, '[^A-Za-z]', '', 'g') FROM 1 FOR 3))
    """

    # Handle any empty prefixes (from names with no letters)
    execute """
    UPDATE workspaces
    SET task_prefix = 'WS'
    WHERE task_prefix IS NULL OR task_prefix = ''
    """

    alter table(:workspaces) do
      modify :task_prefix, :text, null: false
    end
  end

  def down do
    alter table(:workspaces) do
      remove :task_prefix
    end
  end
end
