defmodule Citadel.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:tasks, "tasks_parent_task_id_fkey")

    alter table(:tasks) do
      modify :parent_task_id,
             references(:tasks,
               column: :id,
               name: "tasks_parent_task_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:tasks, [:workspace_id, :parent_task_id])
  end

  def down do
    drop_if_exists index(:tasks, [:workspace_id, :parent_task_id])

    drop constraint(:tasks, "tasks_parent_task_id_fkey")

    alter table(:tasks) do
      modify :parent_task_id,
             references(:tasks,
               column: :id,
               name: "tasks_parent_task_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
