defmodule Citadel.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Step 1: For workspace owners who have an org, assign that org to their workspaces
    execute """
    UPDATE workspaces w
    SET organization_id = (
      SELECT om.organization_id
      FROM organization_memberships om
      WHERE om.user_id = w.owner_id
      LIMIT 1
    )
    WHERE w.organization_id IS NULL
    AND EXISTS (
      SELECT 1 FROM organization_memberships om
      WHERE om.user_id = w.owner_id
    )
    """

    # Step 2: For workspace owners without an org, create one and assign it
    # This uses a CTE to create organizations and memberships, then updates workspaces
    execute """
    WITH owners_needing_orgs AS (
      SELECT DISTINCT w.owner_id
      FROM workspaces w
      WHERE w.organization_id IS NULL
      AND NOT EXISTS (
        SELECT 1 FROM organization_memberships om
        WHERE om.user_id = w.owner_id
      )
    ),
    new_orgs AS (
      INSERT INTO organizations (id, name, slug, owner_id, inserted_at, updated_at)
      SELECT
        gen_random_uuid(),
        'Personal',
        'personal-' || SUBSTRING(o.owner_id::text, 1, 8),
        o.owner_id,
        NOW(),
        NOW()
      FROM owners_needing_orgs o
      RETURNING id, owner_id
    ),
    new_memberships AS (
      INSERT INTO organization_memberships (id, organization_id, user_id, role, inserted_at, updated_at)
      SELECT
        gen_random_uuid(),
        no.id,
        no.owner_id,
        'owner',
        NOW(),
        NOW()
      FROM new_orgs no
      RETURNING organization_id, user_id
    )
    UPDATE workspaces w
    SET organization_id = nm.organization_id
    FROM new_memberships nm
    WHERE w.owner_id = nm.user_id
    AND w.organization_id IS NULL
    """

    alter table(:workspaces) do
      modify :organization_id, :uuid, null: false
    end
  end

  def down do
    alter table(:workspaces) do
      modify :organization_id, :uuid, null: true
    end
  end
end
