defmodule Citadel.Repo.Migrations.CascadeTaskDeletes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:tasks, "tasks_parent_task_id_fkey")

    alter table(:tasks) do
      modify :parent_task_id,
             references(:tasks,
               column: :id,
               name: "tasks_parent_task_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:tasks, "tasks_parent_task_id_fkey")

    alter table(:tasks) do
      modify :parent_task_id,
             references(:tasks,
               column: :id,
               name: "tasks_parent_task_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
