defmodule Citadel.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workspace_task_counters, primary_key: false) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "workspace_task_counters_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false

      add :last_task_number, :bigint, null: false, default: 0
    end

    # Initialize counters for existing workspaces
    execute """
    INSERT INTO workspace_task_counters (workspace_id, last_task_number)
    SELECT id, 0 FROM workspaces
    """
  end

  def down do
    drop constraint(:workspace_task_counters, "workspace_task_counters_workspace_id_fkey")

    drop table(:workspace_task_counters)
  end
end
