defmodule Citadel.Repo.Migrations.AddIconAndColorsToStates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:task_states) do
      add_if_not_exists :icon, :text
      add_if_not_exists :foreground_color, :text
      add_if_not_exists :background_color, :text
    end
  end

  def down do
    alter table(:task_states) do
      remove :background_color
      remove :foreground_color
      remove :icon
    end
  end
end
