defmodule Citadel.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:processed_webhook_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :stripe_event_id, :text, null: false
      add :event_type, :text

      add :processed_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:processed_webhook_events, [:stripe_event_id],
             name: "processed_webhook_events_unique_stripe_event_index"
           )
  end

  def down do
    drop_if_exists unique_index(:processed_webhook_events, [:stripe_event_id],
                     name: "processed_webhook_events_unique_stripe_event_index"
                   )

    drop table(:processed_webhook_events)
  end
end
