defmodule Citadel.Repo.Migrations.AddOrganizations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workspaces) do
      add :organization_id, :uuid
    end

    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:workspaces) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "workspaces_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:organizations) do
      add :name, :text, null: false
      add :slug, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "organizations_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    create table(:organization_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :role, :text, null: false, default: "member"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "organization_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "organization_memberships_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false
    end

    create unique_index(:organization_memberships, [:user_id, :organization_id],
             name: "organization_memberships_unique_membership_index"
           )
  end

  def down do
    drop_if_exists unique_index(:organization_memberships, [:user_id, :organization_id],
                     name: "organization_memberships_unique_membership_index"
                   )

    drop constraint(:organization_memberships, "organization_memberships_user_id_fkey")

    drop constraint(:organization_memberships, "organization_memberships_organization_id_fkey")

    drop table(:organization_memberships)

    drop_if_exists unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    drop constraint(:organizations, "organizations_owner_id_fkey")

    alter table(:organizations) do
      remove :owner_id
      remove :updated_at
      remove :inserted_at
      remove :slug
      remove :name
    end

    drop constraint(:workspaces, "workspaces_organization_id_fkey")

    alter table(:workspaces) do
      modify :organization_id, :uuid
    end

    drop table(:organizations)

    alter table(:workspaces) do
      remove :organization_id
    end
  end
end
