defmodule Citadel.Repo.Migrations.AddWorkspaceInvitations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workspace_invitations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :email, :citext, null: false
      add :token, :text, null: false
      add :expires_at, :utc_datetime_usec, null: false
      add :accepted_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "workspace_invitations_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :invited_by_id,
          references(:users,
            column: :id,
            name: "workspace_invitations_invited_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:workspace_invitations, [:token],
             name: "workspace_invitations_unique_token_index"
           )
  end

  def down do
    drop_if_exists unique_index(:workspace_invitations, [:token],
                     name: "workspace_invitations_unique_token_index"
                   )

    drop constraint(:workspace_invitations, "workspace_invitations_workspace_id_fkey")

    drop constraint(:workspace_invitations, "workspace_invitations_invited_by_id_fkey")

    drop table(:workspace_invitations)
  end
end
