defmodule Citadel.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "tasks_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    drop constraint(:messages, "messages_conversation_id_fkey")

    alter table(:messages) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:conversations) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "conversations_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:conversations, "conversations_workspace_id_fkey")

    alter table(:conversations) do
      remove :workspace_id
    end

    drop constraint(:messages, "messages_conversation_id_fkey")

    alter table(:messages) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:tasks, "tasks_workspace_id_fkey")

    alter table(:tasks) do
      remove :workspace_id
    end
  end
end
