defmodule Citadel.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :parent_task_id,
          references(:tasks,
            column: :id,
            name: "tasks_parent_task_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:tasks, "tasks_parent_task_id_fkey")

    alter table(:tasks) do
      remove :parent_task_id
    end
  end
end
