defmodule Citadel.Repo.Migrations.AddAdditioalTaskFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :due_date, :date
      add :priority, :text, default: "medium"
    end

    create table(:task_assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :task_id,
          references(:tasks,
            column: :id,
            name: "task_assignments_task_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :assignee_id,
          references(:users,
            column: :id,
            name: "task_assignments_assignee_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:task_assignments, [:task_id])

    create index(:task_assignments, [:assignee_id])

    create unique_index(:task_assignments, [:task_id, :assignee_id],
             name: "task_assignments_unique_assignment_index"
           )
  end

  def down do
    drop_if_exists unique_index(:task_assignments, [:task_id, :assignee_id],
                     name: "task_assignments_unique_assignment_index"
                   )

    drop_if_exists index(:task_assignments, [:assignee_id])

    drop_if_exists index(:task_assignments, [:task_id])

    drop constraint(:task_assignments, "task_assignments_task_id_fkey")

    drop constraint(:task_assignments, "task_assignments_assignee_id_fkey")

    drop table(:task_assignments)

    alter table(:tasks) do
      remove :priority
      remove :due_date
    end
  end
end
