defmodule Citadel.Repo.Migrations.AddHumanReadableIds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workspaces) do
      add :task_prefix, :text
    end

    # Backfill existing workspaces with prefix derived from name
    execute """
    UPDATE workspaces
    SET task_prefix = UPPER(SUBSTRING(REGEXP_REPLACE(name, '[^A-Za-z]', '', 'g') FROM 1 FOR 3))
    """

    # Handle any empty prefixes (from names with no letters)
    execute """
    UPDATE workspaces
    SET task_prefix = 'WS'
    WHERE task_prefix IS NULL OR task_prefix = ''
    """

    alter table(:workspaces) do
      modify :task_prefix, :text, null: false
    end

    create table(:workspace_task_counters, primary_key: false) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "workspace_task_counters_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :last_task_number, :bigint, null: false, default: 0
    end

    # Initialize counters for existing workspaces
    execute """
    INSERT INTO workspace_task_counters (workspace_id, last_task_number)
    SELECT id, 0 FROM workspaces
    """

    alter table(:tasks) do
      add :human_id, :text
    end

    # Backfill existing tasks with human_ids
    # Assigns sequential numbers per workspace based on inserted_at order
    execute """
    WITH numbered_tasks AS (
      SELECT
        t.id,
        t.workspace_id,
        w.task_prefix,
        ROW_NUMBER() OVER (PARTITION BY t.workspace_id ORDER BY t.inserted_at) as task_num
      FROM tasks t
      JOIN workspaces w ON w.id = t.workspace_id
    )
    UPDATE tasks
    SET human_id = numbered_tasks.task_prefix || '-' || numbered_tasks.task_num
    FROM numbered_tasks
    WHERE tasks.id = numbered_tasks.id
    """

    # Update counters to reflect the max task number per workspace
    execute """
    UPDATE workspace_task_counters c
    SET last_task_number = COALESCE(
      (SELECT COUNT(*) FROM tasks WHERE workspace_id = c.workspace_id),
      0
    )
    """

    alter table(:tasks) do
      modify :human_id, :text, null: false

      add :parent_task_id,
          references(:tasks,
            column: :id,
            name: "tasks_parent_task_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:tasks, [:workspace_id, :parent_task_id])

    create unique_index(:tasks, [:workspace_id, :human_id], name: "tasks_unique_human_id_index")
  end

  def down do
    drop_if_exists unique_index(:tasks, [:workspace_id, :human_id],
                     name: "tasks_unique_human_id_index"
                   )

    drop_if_exists index(:tasks, [:workspace_id, :parent_task_id])

    drop constraint(:tasks, "tasks_parent_task_id_fkey")

    alter table(:tasks) do
      remove :parent_task_id
      remove :human_id
    end

    drop constraint(:workspace_task_counters, "workspace_task_counters_workspace_id_fkey")

    drop table(:workspace_task_counters)

    alter table(:workspaces) do
      remove :task_prefix
    end
  end
end
