defmodule Citadel.Repo.Migrations.AddBilling do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:subscriptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :tier, :text, null: false, default: "free"
      add :billing_period, :text
      add :stripe_subscription_id, :text
      add :stripe_customer_id, :text
      add :status, :text, null: false, default: "active"
      add :current_period_start, :utc_datetime
      add :current_period_end, :utc_datetime
      add :seat_count, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "subscriptions_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:subscriptions, [:organization_id])

    create unique_index(:subscriptions, [:organization_id],
             name: "subscriptions_unique_organization_index"
           )

    create table(:credit_ledger, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :amount, :bigint, null: false
      add :running_balance, :bigint, null: false
      add :description, :text, null: false
      add :transaction_type, :text, null: false
      add :reference_type, :text
      add :reference_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "credit_ledger_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:credit_ledger, [:organization_id, :inserted_at])

    create index(:credit_ledger, [:organization_id])
  end

  def down do
    drop_if_exists index(:credit_ledger, [:organization_id])

    drop constraint(:credit_ledger, "credit_ledger_organization_id_fkey")

    drop_if_exists index(:credit_ledger, [:organization_id, :inserted_at])

    drop table(:credit_ledger)

    drop_if_exists unique_index(:subscriptions, [:organization_id],
                     name: "subscriptions_unique_organization_index"
                   )

    drop_if_exists index(:subscriptions, [:organization_id])

    drop constraint(:subscriptions, "subscriptions_organization_id_fkey")

    drop table(:subscriptions)
  end
end
