defmodule Citadel.Repo.Migrations.AddApiKeyAuth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:workspace_memberships, "workspace_memberships_workspace_id_fkey")

    alter table(:workspace_memberships) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "workspace_memberships_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:tasks) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "tasks_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    drop constraint(:messages, "messages_conversation_id_fkey")

    alter table(:messages) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:conversations) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "conversations_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create table(:api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :api_key_hash, :binary, null: false
      add :expires_at, :utc_datetime_usec, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "api_keys_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")
  end

  def down do
    drop_if_exists unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")

    drop constraint(:api_keys, "api_keys_user_id_fkey")

    drop table(:api_keys)

    drop constraint(:conversations, "conversations_workspace_id_fkey")

    alter table(:conversations) do
      remove :workspace_id
    end

    drop constraint(:messages, "messages_conversation_id_fkey")

    alter table(:messages) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:tasks, "tasks_workspace_id_fkey")

    alter table(:tasks) do
      remove :workspace_id
    end

    drop constraint(:workspace_memberships, "workspace_memberships_workspace_id_fkey")

    alter table(:workspace_memberships) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "workspace_memberships_workspace_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
