defmodule Citadel.Repo.Migrations.AddGithubConnection do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:messages, [:id], name: "messages_unique_id_index")

    create table(:github_connections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :pat_encrypted, :binary, null: false
      add :github_username, :text

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "github_connections_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:github_connections, [:workspace_id],
             name: "github_connections_unique_workspace_index"
           )
  end

  def down do
    drop_if_exists unique_index(:github_connections, [:workspace_id],
                     name: "github_connections_unique_workspace_index"
                   )

    drop constraint(:github_connections, "github_connections_workspace_id_fkey")

    drop table(:github_connections)

    drop_if_exists unique_index(:messages, [:id], name: "messages_unique_id_index")
  end
end
