defmodule Citadel.Repo.Migrations.AddWorkspaceMemberships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workspace_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "workspace_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "workspace_memberships_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    create unique_index(:workspace_memberships, [:user_id, :workspace_id],
             name: "workspace_memberships_unique_membership_index"
           )
  end

  def down do
    drop_if_exists unique_index(:workspace_memberships, [:user_id, :workspace_id],
                     name: "workspace_memberships_unique_membership_index"
                   )

    drop constraint(:workspace_memberships, "workspace_memberships_user_id_fkey")

    drop constraint(:workspace_memberships, "workspace_memberships_workspace_id_fkey")

    drop table(:workspace_memberships)
  end
end
