defmodule Citadel.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :human_id, :text
    end

    # Backfill existing tasks with human_ids
    # Assigns sequential numbers per workspace based on inserted_at order
    execute """
    WITH numbered_tasks AS (
      SELECT
        t.id,
        t.workspace_id,
        w.task_prefix,
        ROW_NUMBER() OVER (PARTITION BY t.workspace_id ORDER BY t.inserted_at) as task_num
      FROM tasks t
      JOIN workspaces w ON w.id = t.workspace_id
    )
    UPDATE tasks
    SET human_id = numbered_tasks.task_prefix || '-' || numbered_tasks.task_num
    FROM numbered_tasks
    WHERE tasks.id = numbered_tasks.id
    """

    # Update counters to reflect the max task number per workspace
    execute """
    UPDATE workspace_task_counters c
    SET last_task_number = COALESCE(
      (SELECT COUNT(*) FROM tasks WHERE workspace_id = c.workspace_id),
      0
    )
    """

    alter table(:tasks) do
      modify :human_id, :text, null: false
    end

    create unique_index(:tasks, [:workspace_id, :human_id], name: "tasks_unique_human_id_index")
  end

  def down do
    drop_if_exists unique_index(:tasks, [:workspace_id, :human_id],
                     name: "tasks_unique_human_id_index"
                   )

    alter table(:tasks) do
      remove :human_id
    end
  end
end
