defmodule Citadel.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:workspace_memberships, "workspace_memberships_workspace_id_fkey")

    alter table(:workspace_memberships) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "workspace_memberships_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:workspace_memberships, "workspace_memberships_workspace_id_fkey")

    alter table(:workspace_memberships) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "workspace_memberships_workspace_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
