defmodule Citadel.Repo.Migrations.TaskActivityQuestionsAndResponses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:task_activities) do
      add :parent_activity_id,
          references(:task_activities,
            column: :id,
            name: "task_activities_parent_activity_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    alter table(:agent_work_items) do
      add :session_id, :text
    end
  end

  def down do
    alter table(:agent_work_items) do
      remove :session_id
    end

    drop constraint(:task_activities, "task_activities_parent_activity_id_fkey")

    alter table(:task_activities) do
      remove :parent_activity_id
    end
  end
end
