defmodule Citadel.Repo.Migrations.AddUniqueIndexToTaskStateName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:task_states, [:name])
    create unique_index(:task_states, [:name], name: "task_states_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:task_states, [:name], name: "task_states_unique_name_index")
    create unique_index(:task_states, [:name])
  end
end
