defmodule Citadel.Repo.Migrations.DropLogsFromAgentRun do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agent_runs) do
      remove :logs
    end
  end

  def down do
    alter table(:agent_runs) do
      add :logs, :text
    end
  end
end
