defmodule Citadel.Repo.Migrations.AddAgentRun do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :agent_eligible, :boolean, default: false
    end

    create table(:agent_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :status, :text, null: false, default: "pending"
      add :diff, :text
      add :test_output, :text
      add :logs, :text
      add :error_message, :text
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "agent_runs_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :task_id,
          references(:tasks,
            column: :id,
            name: "agent_runs_task_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "agent_runs_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:agent_runs, "agent_runs_workspace_id_fkey")

    drop constraint(:agent_runs, "agent_runs_task_id_fkey")

    drop constraint(:agent_runs, "agent_runs_user_id_fkey")

    drop table(:agent_runs)

    alter table(:tasks) do
      remove :agent_eligible
    end
  end
end
