defmodule Citadel.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agent_runs) do
      remove :diff
      add :commits, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:agent_runs) do
      remove :commits
      add :diff, :text
    end
  end
end
