defmodule Citadel.Repo.Migrations.ReplaceDiffWithCommitsOnAgentRun do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :forge_pr, :text
    end

    alter table(:agent_runs) do
      remove :diff
      add :commits, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:agent_runs) do
      remove :commits
      add :diff, :text
    end

    alter table(:tasks) do
      remove :forge_pr
    end
  end
end
