defmodule Citadel.Repo.Migrations.AddAgentWorkItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_work_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :type, :text, null: false
      add :status, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "agent_work_items_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :task_id,
          references(:tasks,
            column: :id,
            name: "agent_work_items_task_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :comment_id,
          references(:task_activities,
            column: :id,
            name: "agent_work_items_comment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :agent_run_id,
          references(:agent_runs,
            column: :id,
            name: "agent_work_items_agent_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:agent_work_items, [:workspace_id, :task_id],
             name: "agent_work_items_one_active_per_task",
             unique: true,
             where: "status IN ('pending', 'claimed')"
           )
  end

  def down do
    drop constraint(:agent_work_items, "agent_work_items_workspace_id_fkey")

    drop constraint(:agent_work_items, "agent_work_items_task_id_fkey")

    drop constraint(:agent_work_items, "agent_work_items_comment_id_fkey")

    drop constraint(:agent_work_items, "agent_work_items_agent_run_id_fkey")

    drop_if_exists index(:agent_work_items, [:workspace_id, :task_id],
                     name: "agent_work_items_one_active_per_task"
                   )

    drop table(:agent_work_items)
  end
end
