defmodule Citadel.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :forge_pr, :text
    end
  end

  def down do
    alter table(:tasks) do
      remove :forge_pr
    end
  end
end
