defmodule Citadel.Repo.Migrations.AddAgentRunEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_run_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :event_type, :text, null: false
      add :message, :text
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "agent_run_events_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :agent_run_id,
          references(:agent_runs,
            column: :id,
            name: "agent_run_events_agent_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:agent_run_events, "agent_run_events_workspace_id_fkey")

    drop constraint(:agent_run_events, "agent_run_events_agent_run_id_fkey")

    drop table(:agent_run_events)
  end
end
