defmodule Citadel.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :project_id,
          references(:projects,
            column: :id,
            name: "tasks_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :active_agent_run_id,
          references(:agent_runs,
            column: :id,
            name: "tasks_active_agent_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:tasks, [:workspace_id, :project_id])

    create index(:tasks, [:workspace_id, :active_agent_run_id])
  end

  def down do
    drop_if_exists index(:tasks, [:workspace_id, :active_agent_run_id])

    drop_if_exists index(:tasks, [:workspace_id, :project_id])

    drop constraint(:tasks, "tasks_project_id_fkey")

    drop constraint(:tasks, "tasks_active_agent_run_id_fkey")

    alter table(:tasks) do
      remove :active_agent_run_id
      remove :project_id
    end
  end
end
