defmodule Citadel.Repo.Migrations.EventSinkEnhancements do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:tasks, "tasks_active_agent_run_id_fkey")

    alter table(:tasks) do
      modify :active_agent_run_id,
             references(:agent_runs,
               column: :id,
               name: "tasks_active_agent_run_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    drop constraint(:refinement_cycles, "refinement_cycles_agent_run_id_fkey")

    alter table(:refinement_cycles) do
      modify :agent_run_id,
             references(:agent_runs,
               column: :id,
               name: "refinement_cycles_agent_run_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:agent_work_items, "agent_work_items_agent_run_id_fkey")

    alter table(:agent_work_items) do
      modify :agent_run_id,
             references(:agent_runs,
               column: :id,
               name: "agent_work_items_agent_run_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:agent_runs) do
      add :last_activity_at, :utc_datetime_usec
      add :stall_status, :text
    end

    drop constraint(:agent_run_events, "agent_run_events_agent_run_id_fkey")

    alter table(:agent_run_events) do
      add :dedup_key, :text

      modify :agent_run_id,
             references(:agent_runs,
               column: :id,
               name: "agent_run_events_agent_run_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:agent_run_events, [:workspace_id, :dedup_key],
             name: "agent_run_events_unique_dedup_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:agent_run_events, [:workspace_id, :dedup_key],
                     name: "agent_run_events_unique_dedup_key_index"
                   )

    drop constraint(:agent_run_events, "agent_run_events_agent_run_id_fkey")

    alter table(:agent_run_events) do
      modify :agent_run_id,
             references(:agent_runs,
               column: :id,
               name: "agent_run_events_agent_run_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      remove :dedup_key
    end

    alter table(:agent_runs) do
      remove :stall_status
      remove :last_activity_at
    end

    drop constraint(:agent_work_items, "agent_work_items_agent_run_id_fkey")

    alter table(:agent_work_items) do
      modify :agent_run_id,
             references(:agent_runs,
               column: :id,
               name: "agent_work_items_agent_run_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    drop constraint(:refinement_cycles, "refinement_cycles_agent_run_id_fkey")

    alter table(:refinement_cycles) do
      modify :agent_run_id,
             references(:agent_runs,
               column: :id,
               name: "refinement_cycles_agent_run_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:tasks, "tasks_active_agent_run_id_fkey")

    alter table(:tasks) do
      modify :active_agent_run_id,
             references(:agent_runs,
               column: :id,
               name: "tasks_active_agent_run_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end
  end
end
