defmodule Citadel.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agent_runs) do
      add :session_id, :text
    end
  end

  def down do
    alter table(:agent_runs) do
      remove :session_id
    end
  end
end
