defmodule Citadel.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:task_dependencies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :task_id,
          references(:tasks,
            column: :id,
            name: "task_dependencies_task_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :depends_on_task_id,
          references(:tasks,
            column: :id,
            name: "task_dependencies_depends_on_task_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:task_dependencies, [:task_id])

    create index(:task_dependencies, [:depends_on_task_id])

    create unique_index(:task_dependencies, [:task_id, :depends_on_task_id],
             name: "task_dependencies_unique_dependency_index"
           )

    create constraint(:task_dependencies, :no_self_reference,
             check: """
               task_id != depends_on_task_id
             """
           )
  end

  def down do
    drop_if_exists constraint(:task_dependencies, :no_self_reference)

    drop_if_exists unique_index(:task_dependencies, [:task_id, :depends_on_task_id],
                     name: "task_dependencies_unique_dependency_index"
                   )

    drop_if_exists index(:task_dependencies, [:depends_on_task_id])

    drop_if_exists index(:task_dependencies, [:task_id])

    drop constraint(:task_dependencies, "task_dependencies_task_id_fkey")

    drop constraint(:task_dependencies, "task_dependencies_depends_on_task_id_fkey")

    drop table(:task_dependencies)
  end
end
