defmodule Citadel.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # agent_run_id column and FK already exist from a previous dev migration
    :ok
  end

  def down do
    :ok
  end
end
