defmodule Citadel.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agent_work_items) do
      add :session_id, :text
    end
  end

  def down do
    alter table(:agent_work_items) do
      remove :session_id
    end
  end
end
