defmodule Citadel.Repo.Migrations.AddModelConfig do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:model_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :provider, :text, null: false
      add :model, :text, null: false
      add :temperature, :float, default: 0.7
      add :max_tokens, :bigint
      add :is_default, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "model_configs_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:model_configs, [:workspace_id, :name],
             name: "model_configs_unique_name_per_workspace_index"
           )
  end

  def down do
    drop_if_exists unique_index(:model_configs, [:workspace_id, :name],
                     name: "model_configs_unique_name_per_workspace_index"
                   )

    drop constraint(:model_configs, "model_configs_workspace_id_fkey")

    drop table(:model_configs)
  end
end
