defmodule Citadel.Repo.Migrations.AgentMaxRunSeconds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workspaces) do
      add :agent_max_run_seconds, :bigint, null: false, default: 14400
    end
  end

  def down do
    alter table(:workspaces) do
      remove :agent_max_run_seconds
    end
  end
end
