defmodule Citadel.Repo.Migrations.AddRefinementTracking do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:refinement_iterations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :iteration_number, :bigint, null: false
      add :evaluation_result, :map, default: %{}
      add :score, :float
      add :feedback, :text
      add :status, :text, null: false, default: "evaluated"
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "refinement_iterations_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :refinement_cycle_id, :uuid, null: false
    end

    create table(:refinement_cycles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:refinement_iterations) do
      modify :refinement_cycle_id,
             references(:refinement_cycles,
               column: :id,
               name: "refinement_iterations_refinement_cycle_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:refinement_cycles) do
      add :status, :text, null: false, default: "running"
      add :max_iterations, :bigint, null: false, default: 3
      add :current_iteration, :bigint, null: false, default: 0
      add :evaluator_config, :map, default: %{}
      add :final_score, :float

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "refinement_cycles_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :agent_run_id,
          references(:agent_runs,
            column: :id,
            name: "refinement_cycles_agent_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:refinement_cycles, "refinement_cycles_workspace_id_fkey")

    drop constraint(:refinement_cycles, "refinement_cycles_agent_run_id_fkey")

    alter table(:refinement_cycles) do
      remove :agent_run_id
      remove :workspace_id
      remove :updated_at
      remove :inserted_at
      remove :final_score
      remove :evaluator_config
      remove :current_iteration
      remove :max_iterations
      remove :status
    end

    drop constraint(:refinement_iterations, "refinement_iterations_refinement_cycle_id_fkey")

    alter table(:refinement_iterations) do
      modify :refinement_cycle_id, :uuid
    end

    drop table(:refinement_cycles)

    drop constraint(:refinement_iterations, "refinement_iterations_workspace_id_fkey")

    drop table(:refinement_iterations)
  end
end
