defmodule Citadel.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:task_activities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :type, :text, null: false, default: "comment"
      add :body, :text
      add :metadata, :map, default: %{}
      add :actor_type, :text, null: false, default: "user"
      add :actor_display_name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "task_activities_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :task_id,
          references(:tasks,
            column: :id,
            name: "task_activities_task_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "task_activities_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:task_activities, "task_activities_workspace_id_fkey")

    drop constraint(:task_activities, "task_activities_task_id_fkey")

    drop constraint(:task_activities, "task_activities_user_id_fkey")

    drop table(:task_activities)
  end
end
