defmodule Citadel.Repo.Migrations.AddTaskAgentConfig do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :refinement_config, :map

      add :model_config_id,
          references(:model_configs,
            column: :id,
            name: "tasks_model_config_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:tasks, [:workspace_id, :model_config_id])
  end

  def down do
    drop_if_exists index(:tasks, [:workspace_id, :model_config_id])

    drop constraint(:tasks, "tasks_model_config_id_fkey")

    alter table(:tasks) do
      remove :model_config_id
      remove :refinement_config
    end
  end
end
