defmodule Citadel.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :repository_url, :text, null: false
      add :default_branch, :text, default: "main"
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "projects_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:projects, [:workspace_id, :repository_url],
             name: "projects_unique_repo_per_workspace_index"
           )
  end

  def down do
    drop_if_exists unique_index(:projects, [:workspace_id, :repository_url],
                     name: "projects_unique_repo_per_workspace_index"
                   )

    drop constraint(:projects, "projects_workspace_id_fkey")

    drop table(:projects)
  end
end
